version: '2'

services:
  jenkins:
    image: docker.io/bitnami/jenkins:2
    ports:
      - '8280:8080'
    environment:
      - JENKINS_PASSWORD=root@admin
      - JENKINS_USER=root
    volumes:
      - 'jenkins_data:/bitnami/jenkins'

volumes:
  jenkins_data:
    driver: local
