version: '2'

services:
  jenkins:
    image: jenkins/jenkins:jdk11
    ports:
      - '8280:8080'
    environment:
      - JENKINS_PASSWORD=root@admin
      - JENKINS_USERNAME=root
    volumes:
      - 'jenkins_data:/jenkins'

volumes:
  jenkins_data:
    driver: local
